name: Tests

on:
  push:
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container:
      image: ccmbenchmark/php:7.1
    steps:
      - uses: actions/checkout@v2
      - name: Install vendors
        run: composer install --prefer-source --no-interaction
      - name: Run Atoum tests
        run: php vendor/bin/atoum
 